package com.JoysToysApplication.JoysToysApplication.DTO;


public class CustomerOrderDTO {

    //this is the stuff that is not autogenerated
    private long customer_id;

    private long product_id;

    private int quantity;

    public CustomerOrderDTO() {

    }

    public CustomerOrderDTO(long customer_id, long product_id, int quantity) {
        this.customer_id = customer_id;
        this.product_id = product_id;
        this.quantity = quantity;
    }

    public long getCustomer_id() {
        return customer_id;
    }

    public long getProduct_id() {
        return product_id;
    }

    public int getQuantity() {
        return quantity;
    }

    public void setCustomer_id(long customer_id) {
        this.customer_id = customer_id;
    }

    public void setProduct_id(long product_id) {
        this.product_id = product_id;
    }

    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }
}
